// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-yeih3KmQ_fV3UJATqzjRQml0uFaa_g',
    appId: '1:558552038453:web:17f6ab2945d73e4072c57c',
    messagingSenderId: '558552038453',
    projectId: 'fiscore-dev',
    authDomain: 'fiscore-dev.firebaseapp.com',
    storageBucket: 'fiscore-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrAo1gcishgW9aODClUP6m2b-1eOlRuE',
    appId: '1:558552038453:android:31327039e013b3bd72c57c',
    messagingSenderId: '558552038453',
    projectId: 'fiscore-dev',
    storageBucket: 'fiscore-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnTqYfV_WDm4lGYItCZvOo-hAGZzrtW0',
    appId: '1:558552038453:ios:67a31603ea78b8ef72c57c',
    messagingSenderId: '558552038453',
    projectId: 'fiscore-dev',
    storageBucket: 'fiscore-dev.firebasestorage.app',
    androidClientId: '558552038453-jmhvpg36lfnlmr6ea8164n2qn3h17mlt.apps.googleusercontent.com',
    iosClientId: '558552038453-b4rdo5mh65apq4imi3blo2itd64bb28g.apps.googleusercontent.com',
    iosBundleId: 'com.pioneeritworks.fiscore.dev',
  );
}
