const starterChecklistLibrary = {
  food_safety_walkthrough: {
    id: "food_safety_walkthrough",
    name: "Food Safety Walkthrough",
    description: "Review core food safety controls and capture follow-up work.",
    category: "food_safety",
    templateSource: "library_synced",
    templateScope: "tenant",
    libraryTemplateId: "food_safety_walkthrough",
    libraryVersion: 1,
    syncMode: "synced_from_library",
    syncStatus: "up_to_date",
    status: "active",
    sectionCount: 4,
    questionCount: 8,
    estimatedMinutes: 10,
    version: 1,
    sections: [
      {
        id: "hygiene",
        title: "Handwashing and hygiene",
        questions: [
          {
            id: "handwash_supplies",
            prompt: "Handwashing sinks are supplied and accessible.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "employee_hygiene",
            prompt: "Employees follow appropriate hygiene and glove practices.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
      {
        id: "temperature",
        title: "Temperature and date marking",
        questions: [
          {
            id: "cold_holding",
            prompt: "Cold-held food is maintained at a safe temperature.",
            failSeverity: "critical",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "date_marking",
            prompt: "Prepared food is labeled and date marked correctly.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
      {
        id: "sanitation",
        title: "Cleaning and sanitation",
        questions: [
          {
            id: "food_contact_surfaces",
            prompt: "Food-contact surfaces are clean and sanitized.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "chemical_storage",
            prompt: "Chemicals are labeled and stored away from food.",
            failSeverity: "critical",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
      {
        id: "storage",
        title: "Storage and contamination prevention",
        questions: [
          {
            id: "food_storage",
            prompt: "Food is covered and stored to prevent contamination.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "pest_activity",
            prompt: "No evidence of pest activity is observed.",
            failSeverity: "critical",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
    ],
  },
  opening_readiness_check: {
    id: "opening_readiness_check",
    name: "Opening Readiness Check",
    description: "Confirm the kitchen is ready for a safe opening shift.",
    category: "opening",
    templateSource: "library_synced",
    templateScope: "tenant",
    libraryTemplateId: "opening_readiness_check",
    libraryVersion: 1,
    syncMode: "synced_from_library",
    syncStatus: "up_to_date",
    status: "active",
    sectionCount: 2,
    questionCount: 6,
    estimatedMinutes: 3,
    version: 1,
    sections: [
      {
        id: "opening_setup",
        title: "Opening setup",
        questions: [
          {
            id: "opening_handwash",
            prompt: "Handwashing stations have soap and paper towels.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "sanitizer_ready",
            prompt: "Sanitizer solution and test strips are ready for use.",
            failSeverity: "minor",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "equipment_ready",
            prompt: "Cold-holding equipment is operating and clean.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
      {
        id: "food_readiness",
        title: "Food readiness",
        questions: [
          {
            id: "opening_temperatures",
            prompt: "Required opening temperatures are within safe limits.",
            failSeverity: "critical",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "opening_labels",
            prompt: "Prepared items are labeled and dated before service.",
            failSeverity: "major",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
          {
            id: "service_area_clean",
            prompt: "Service and preparation areas are clean and ready.",
            failSeverity: "minor",
            createsViolation: true,
            requiresNoteOnFail: true,
          },
        ],
      },
    ],
  },
};

const starterTrainingLibrary = {
  handwashing_basics: {
    title: "Handwashing and glove use",
    description: "Keep hands, sinks, and glove changes ready for service.",
    trainingSource: "library_synced",
    libraryTrainingId: "handwashing_basics",
    libraryVersion: 2,
    syncMode: "synced_from_library",
    syncStatus: "up_to_date",
    trainingType: "micro_learning",
    durationMinutes: 3,
    riskArea: "handwashing",
    relatedRiskAreas: ["handwashing"],
    version: 2,
    status: "active",
    hasQuickCheck: true,
    topicSummaries: [
      "When handwashing is required",
      "Keeping sinks supplied and accessible",
      "Changing gloves at the right time",
    ],
    sections: [
      {
        id: "wash_before_work",
        title: "Wash hands at the right moments",
        body: "Wash before starting food work, after touching anything that can contaminate hands, and before putting on new gloves.",
        actionTip: "Gloves never replace handwashing.",
      },
      {
        id: "stock_sinks",
        title: "Keep the hand sink ready",
        body: "A hand sink must stay accessible and supplied with soap and paper towels during service.",
        actionTip: "Report or refill missing supplies immediately.",
      },
      {
        id: "change_gloves",
        title: "Change gloves when work changes",
        body: "Replace gloves after contamination, between raw and ready-to-eat food, and when gloves become torn or dirty.",
        actionTip: "Wash hands before putting on a clean pair.",
      },
    ],
    quickCheckQuestions: [
      {
        id: "gloves_replace_washing",
        prompt: "Can clean gloves replace handwashing before food prep?",
        options: ["Yes", "No"],
        correctOptionIndex: 1,
        explanation: "Hands must be washed before new gloves are put on.",
      },
      {
        id: "blocked_sink",
        prompt: "What should you do if a hand sink is blocked or out of paper towels?",
        options: [
          "Keep working until the rush ends",
          "Make it accessible and restore supplies immediately",
          "Use a food-prep sink instead",
        ],
        correctOptionIndex: 1,
        explanation: "Handwashing facilities must stay accessible and supplied during work.",
      },
    ],
  },
  date_marking_storage: {
    title: "Date marking and food storage",
    description: "Label prepared food correctly and remove expired items.",
    trainingSource: "library_synced",
    libraryTrainingId: "date_marking_storage",
    libraryVersion: 2,
    syncMode: "synced_from_library",
    syncStatus: "up_to_date",
    trainingType: "micro_learning",
    durationMinutes: 4,
    riskArea: "date_marking",
    relatedRiskAreas: ["date_marking", "temperature_control"],
    version: 2,
    status: "active",
    hasQuickCheck: true,
    topicSummaries: [
      "Apply prep and discard dates",
      "Check labels during every shift",
      "Discard food past its hold date",
    ],
    sections: [
      {
        id: "label_food",
        title: "Label food when it is prepared",
        body: "Mark prepared or opened refrigerated food with the required prep/open date and discard date before it is placed into storage.",
        actionTip: "A label is easiest to verify when it is applied right away.",
      },
      {
        id: "check_each_shift",
        title: "Check labels during each shift",
        body: "Look for missing, unreadable, or expired date marks while stocking and during routine cooler checks.",
        actionTip: "Correct missing labels before food is used.",
      },
      {
        id: "discard_expired",
        title: "Remove food past the hold date",
        body: "Food that is past its permitted hold date should be discarded, not relabeled for later use.",
        actionTip: "When in doubt, pause and ask a manager.",
      },
    ],
    quickCheckQuestions: [
      {
        id: "when_label",
        prompt: "When should prepared refrigerated food be date marked?",
        options: [
          "Before it is placed into storage",
          "At the end of the week",
          "Only if an inspector visits",
        ],
        correctOptionIndex: 0,
        explanation: "Food should be labeled when prepared or opened, before storage.",
      },
      {
        id: "expired_food",
        prompt: "What should happen to food past its discard date?",
        options: ["Relabel it", "Discard it", "Mix it with newer food"],
        correctOptionIndex: 1,
        explanation: "Expired food must be removed rather than relabeled.",
      },
    ],
  },
  cleaning_sanitizer: {
    title: "Cleaning and sanitizer readiness",
    description: "Use sanitizer safely and prevent contamination with visual guidance.",
    trainingSource: "library_synced",
    libraryTrainingId: "cleaning_sanitizer",
    libraryVersion: 3,
    syncMode: "synced_from_library",
    syncStatus: "up_to_date",
    trainingType: "micro_learning",
    durationMinutes: 6,
    contentFormat: "visual_lesson",
    mediaSummary: "Video lesson",
    riskArea: "cleaning_and_sanitizing",
    relatedRiskAreas: ["cleaning_and_sanitizing", "chemical_safety"],
    version: 3,
    status: "active",
    hasQuickCheck: true,
    topicSummaries: [
      "Prepare sanitizer correctly",
      "Keep chemicals away from food",
      "Clean food-contact surfaces",
    ],
    mediaAssets: {
      med_sanitizer_strip_01: {
        id: "med_sanitizer_strip_01",
        type: "image",
        fileName: "sanitizer-test-strips.jpg",
        contentType: "image/jpeg",
        storagePath: "fiscoreLibrary/training/cleaning_sanitizer/versions/3/media/med_sanitizer_strip_01/image.jpg",
        altText: "Sanitizer test strip compared with an approved concentration range.",
      },
      med_chemical_storage_01: {
        id: "med_chemical_storage_01",
        type: "image",
        fileName: "chemical-storage.jpg",
        contentType: "image/jpeg",
        storagePath: "fiscoreLibrary/training/cleaning_sanitizer/versions/3/media/med_chemical_storage_01/image.jpg",
        altText: "Cleaning chemicals stored below and separated from food and utensils.",
      },
      med_cleaning_demo_01: {
        id: "med_cleaning_demo_01",
        type: "video",
        fileName: "cleaning-and-sanitation-required.mp4",
        contentType: "video/mp4",
        storagePath: "fiscoreLibrary/training/cleaning_sanitizer/versions/3/media/med_cleaning_demo_01/video.mp4",
        durationLabel: "2 min",
        required: true,
      },
    },
    sections: [
      {
        id: "prepare_sanitizer",
        title: "Prepare sanitizer correctly",
        body: "Follow the product instructions and verify sanitizer strength with the correct test strips before use.",
        actionTip: "Replace sanitizer solution when it is dirty or outside the safe range.",
        blocks: [
          {
            type: "text",
            body: "Follow the product instructions and verify sanitizer strength with the correct test strips before use.",
          },
          {
            type: "image",
            mediaId: "med_sanitizer_strip_01",
            caption: "Compare the test strip result to the product's approved concentration range.",
          },
          {
            type: "tip",
            body: "Replace sanitizer solution when it is dirty or outside the safe range.",
          },
        ],
      },
      {
        id: "store_chemicals",
        title: "Keep chemicals away from food",
        body: "Store chemicals in their designated area, away from food, utensils, linens, and preparation surfaces.",
        actionTip: "Never place a chemical bottle above ingredients or clean equipment.",
        blocks: [
          {
            type: "text",
            body: "Store chemicals in their designated area, away from food, utensils, linens, and preparation surfaces.",
          },
          {
            type: "image",
            mediaId: "med_chemical_storage_01",
            caption: "Keep cleaning chemicals in their designated storage area, separated from food and clean tools.",
          },
          {
            type: "tip",
            body: "Never place a chemical bottle above ingredients or clean equipment.",
          },
        ],
      },
      {
        id: "clean_surfaces",
        title: "Clean food-contact surfaces",
        body: "Clean and sanitize food-contact surfaces after contamination and as required during food preparation.",
        actionTip: "Use a clean surface before handling ready-to-eat food.",
        blocks: [
          {
            type: "text",
            body: "Clean and sanitize food-contact surfaces after contamination and as required during food preparation.",
          },
          {
            type: "video",
            mediaId: "med_cleaning_demo_01",
            caption: "Required demonstration: cleaning and sanitizing a food-contact surface",
          },
          {
            type: "tip",
            body: "Use a clean surface before handling ready-to-eat food.",
          },
        ],
      },
    ],
    quickCheckQuestions: [
      {
        id: "test_sanitizer",
        prompt: "How do you confirm sanitizer solution is ready for use?",
        options: [
          "Smell it",
          "Check it with the correct test strips",
          "Use extra soap",
        ],
        correctOptionIndex: 1,
        explanation: "Test strips confirm sanitizer is within the correct range.",
      },
      {
        id: "chemical_storage",
        prompt: "Where should cleaning chemicals be stored?",
        options: [
          "Above food-prep equipment",
          "Next to packaged food",
          "In a designated area away from food and utensils",
        ],
        correctOptionIndex: 2,
        explanation: "Separating chemicals prevents food and equipment contamination.",
      },
    ],
  },
};

module.exports = { starterChecklistLibrary, starterTrainingLibrary };
