insert into ops.platform_registry (
    platform_slug,
    platform_name,
    base_domain,
    status,
    default_parser_id,
    default_parser_version
) values (
    'tyler-environmental-health',
    'Georgia',
    'ga.healthinspections.us',
    'active',
    'ga-healthinspections',
    'ga-healthinspections-v1'
)
on conflict (platform_slug) do update
set
    platform_name = excluded.platform_name,
    base_domain = excluded.base_domain,
    status = excluded.status,
    default_parser_id = excluded.default_parser_id,
    default_parser_version = excluded.default_parser_version,
    updated_at = now();

update ops.source_registry
set
    status = 'inactive',
    updated_at = now()
where source_slug = 'ga_state_food_service';

with counties(county_name) as (
    values
        ('Appling'),
        ('Atkinson'),
        ('Bacon'),
        ('Baker'),
        ('Baldwin'),
        ('Banks'),
        ('Barrow'),
        ('Bartow'),
        ('Ben Hill'),
        ('Berrien'),
        ('Bibb'),
        ('Bleckley'),
        ('Brantley'),
        ('Brooks'),
        ('Bryan'),
        ('Bulloch'),
        ('Burke'),
        ('Butts'),
        ('Calhoun'),
        ('Camden'),
        ('Candler'),
        ('Carroll'),
        ('Catoosa'),
        ('Charlton'),
        ('Chatham'),
        ('Chattahoochee'),
        ('Chattooga'),
        ('Cherokee'),
        ('Clarke'),
        ('Clay'),
        ('Clayton'),
        ('Clinch'),
        ('Cobb'),
        ('Coffee'),
        ('Colquitt'),
        ('Columbia'),
        ('Cook'),
        ('Coweta'),
        ('Crawford'),
        ('Crisp'),
        ('Dade'),
        ('Dawson'),
        ('Decatur'),
        ('DeKalb'),
        ('Dodge'),
        ('Dooly'),
        ('Dougherty'),
        ('Douglas'),
        ('Early'),
        ('Echols'),
        ('Effingham'),
        ('Elbert'),
        ('Emanuel'),
        ('Evans'),
        ('Fannin'),
        ('Fayette'),
        ('Floyd'),
        ('Forsyth'),
        ('Franklin'),
        ('Fulton'),
        ('Gilmer'),
        ('Glascock'),
        ('Glynn'),
        ('Gordon'),
        ('Grady'),
        ('Greene'),
        ('Gwinnett'),
        ('Habersham'),
        ('Hall'),
        ('Hancock'),
        ('Haralson'),
        ('Harris'),
        ('Hart'),
        ('Heard'),
        ('Henry'),
        ('Houston'),
        ('Irwin'),
        ('Jackson'),
        ('Jasper'),
        ('Jeff Davis'),
        ('Jefferson'),
        ('Jenkins'),
        ('Johnson'),
        ('Jones'),
        ('Lamar'),
        ('Lanier'),
        ('Laurens'),
        ('Lee'),
        ('Liberty'),
        ('Lincoln'),
        ('Long'),
        ('Lowndes'),
        ('Lumpkin'),
        ('Macon'),
        ('Madison'),
        ('Marion'),
        ('McDuffie'),
        ('McIntosh'),
        ('Meriwether'),
        ('Miller'),
        ('Mitchell'),
        ('Monroe'),
        ('Montgomery'),
        ('Morgan'),
        ('Murray'),
        ('Muscogee'),
        ('Newton'),
        ('Oconee'),
        ('Oglethorpe'),
        ('Paulding'),
        ('Peach'),
        ('Pickens'),
        ('Pierce'),
        ('Pike'),
        ('Polk'),
        ('Pulaski'),
        ('Putnam'),
        ('Quitman'),
        ('Rabun'),
        ('Randolph'),
        ('Richmond'),
        ('Rockdale'),
        ('Schley'),
        ('Screven'),
        ('Seminole'),
        ('Spalding'),
        ('Stephens'),
        ('Stewart'),
        ('Sumter'),
        ('Talbot'),
        ('Taliaferro'),
        ('Tattnall'),
        ('Taylor'),
        ('Telfair'),
        ('Terrell'),
        ('Thomas'),
        ('Tift'),
        ('Toombs'),
        ('Towns'),
        ('Treutlen'),
        ('Troup'),
        ('Turner'),
        ('Twiggs'),
        ('Union'),
        ('Upson'),
        ('Walker'),
        ('Walton'),
        ('Ware'),
        ('Warren'),
        ('Washington'),
        ('Wayne'),
        ('Webster'),
        ('Wheeler'),
        ('White'),
        ('Whitfield'),
        ('Wilcox'),
        ('Wilkes'),
        ('Wilkinson'),
        ('Worth')
)
insert into ops.source_registry (
    platform_id,
    source_slug,
    source_name,
    platform_name,
    jurisdiction_name,
    source_type,
    base_url,
    source_config,
    cadence_type,
    target_freshness_days,
    parser_id,
    parser_version,
    status
)
select
    (select platform_id from ops.platform_registry where platform_slug = 'tyler-environmental-health'),
    'ga_' || regexp_replace(lower(replace(county_name, ' ', '_')), '[^a-z0-9_]+', '', 'g') || '_food_service',
    'Georgia DPH Food Service - ' || county_name || ' County',
    'Georgia',
    'Georgia - ' || county_name || ' County',
    'html_listing',
    'https://ga.healthinspections.us/stateofgeorgia/',
    jsonb_build_object('county_name', county_name),
    'weekly',
    7,
    'ga-healthinspections',
    'ga-healthinspections-v1',
    'active'
from counties
on conflict (source_slug) do update
set
    platform_id = excluded.platform_id,
    source_name = excluded.source_name,
    platform_name = excluded.platform_name,
    jurisdiction_name = excluded.jurisdiction_name,
    source_type = excluded.source_type,
    base_url = excluded.base_url,
    source_config = excluded.source_config,
    cadence_type = excluded.cadence_type,
    target_freshness_days = excluded.target_freshness_days,
    parser_id = excluded.parser_id,
    parser_version = excluded.parser_version,
    status = excluded.status,
    updated_at = now();
